<?php
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LeantoolSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('lean_tools')->insert([
            ['name'=>'5S','category'=>'','description'=>'Learn the importance and simplicity of 5S, utilize guidelines to ensure each part of 5S is complete, generate 5S progress reports, and learn from the case studies. This tool will explain the importance and simplicity of 5S (or 6S), utilize guidelines to ensure each part of the 5S is complete, generate 5S audit reports, and provide examples of successful 5S case studies.'],
            ['name'=>'A3 Project Report','category'=>'','description'=>'Learn the types of A3, utilize Lean Thinking statements for each category, create A3 Project Reports, access previous ones, and learn from the case studies. This tool is designed help “tell (or document)” your improvement project in a logical and visual way in reference to a particular subject matter. It will provide a consistent approach to learning, applying, and documenting Lean Six Sigma tools by stimulating dialogue and creative problem solving. Four types of A3 Reports will be defined.'],
            ['name'=>'DMAIC','category'=>'','description'=>'This tool documents your improvement project in Six Sigma\'s Design-Measure-Analyze-Improve-Control (D-M-A-I-C) methodology in a visual way in reference to a particular subject matter. It provides a consistent approach to learning, applying, and documenting Lean Six Sigma tools by stimulating dialogue and creative problem solving. The main Lean Six Sigma tools will be thoroughly explained relative to the D-M-A-I-C methodology (along with a Prepare Phase). The D-M-A-I-C Report, the focus of this application, is simple and practical, and will efficiently display relevant information for a continuous improvement or problem solving project.'],
            ['name'=>'Gemba Walk','category'=>'','description'=>'Learn the requirements for a Lean Six Sigma transformation, create a personalized Gemba Walk, access previous ones, and learn from the case studies. This tool helps integrate mission, vision, and values to organizational measurements within a customized Gemba Walk to align everyone within the organization. A Lean Sigma roadmap is detailed in four stages to assist in your Lean Sigma transformation.'],
            ['name'=>'Kaizen Project','category'=>'','description'=>'This tool explains the basics of Kaizen and the types of Kaizen Events. The Standard Kaizen Event will be thoroughly detailed and provide the basic steps through the three phases of the Kaizen Event: Planning, Implementation, and Follow-up. Suggested activities will be provided for each phase, along with the ability to customize for each improvement project.'],
            ['name'=>'Leadership','category'=>'','description'=>'This tool explains the three main approaches to leadership, provides access to over 20 leadership tools and solutions to Kaizen Event issues, allows access to previous solutions as well as suggested Sensei solutions, and provides informative case studies to learn from. It will also assist current and future leaders (managers, supervisors, team leads, etc.) with the savvy know how on when and where to use a particular leadership tool or approach when dealing with people issues during the course of an improvement project. This will help ensure all employees to be better engaged before, during, and after the Kaizen Event.'],
            ['name'=>'Lean Overview and Assessment','category'=>'','description'=>'Understand practical Lean Six Sigma, learn from videos of successful Lean practices, reference Lean Six Sigma books, and review a glossary of Lean terms. This tool is designed for anyone who desires to further their knowledge in Lean Six Sigma.'],
            ['name'=>'Mistake Proofing','category'=>'','description'=>'Learn the importance and benefits of Mistake Proofing to anticipate potential problems before implementing process changes. It helps identify defects before they become major issues in the new process. This tool introduces you to three critical times to apply mistake proofing: (1) before the process starts, (2) during the process itself, and (3) immediately after the process has been completed. This application will significantly help to eliminate errors in the before they become defects in the process.'],
            ['name'=>'PDCA','category'=>'','description'=>'This tool explains the importance and simplicity of the Plan-Do-Check-Act (PDCA) cycle of continuous improvement. It helps clarify some of the basic elements of statistical reasoning and analysis; while providing you with an understanding on how to integrate statistical analysis in your project. You will be introduced to several core statistics as they relate to your industry to collect, organize, analyze, interpret and present data as you gather it in the field.'],
            ['name'=>'Standard Work','category'=>'','description'=>'Learn the importance of Standard Work as being one of the most powerful tools within the Lean Six Sigma toolbox. It is the basis for Kaizen and continuous improvement and will start to create a new discipline within the organization. This tool allows you to document current best practices, analyze them, and create new and better standards to ensure improvements are sustained over time. This application will significantly help to eliminate process variation, and allow for ease of training all employees to the new, improved standard.'],
            ['name'=>'Value Stream Mapping','category'=>'','description'=>'Learn how to quickly document current processes and queue times, identify opportunities for improvement, document metrics, and learn from the case studies. This tool demonstrates how to collect data and identify opportunities for improvement and will allow you to create a value stream map "field report" to immediately share with others.'],
            ['name'=>'Waste Walk ','category'=>'','description'=>'Learn the 12 wastes, conduct a Waste Audit, generate Waste Walk reports, access previous ones, and learn from the case studies. This tool is designed for anyone who wants to improve the work environment by understanding the most basic element of Lean and Six Sigma (i.e., identifying wastes.). Associates, Managers, and Executives with either some or no experience with Lean will benefit from this application.'],
            ['name'=>'5 Whys ','category'=>'Quality Tools','description'=>'Learn the basics on how the 5 Whys Analysis can be used to methodically determine the causes of a problem (or effect). The 5 Whys is closely linked to the Fishbone Diagram and its value is asking "Why?" and "What caused this problem?" numerous times until the root cause is determined. This tool is designed for anyone who wants to effectively solve problems via Total Employee Involvement. Engaging employees in the 5 Whys Analysis will help facilitate solutions to problems or it will generate additional areas of concern that will need to be explored.'],
            ['name'=>'Brainstorming','category'=>'Quality Tools','description'=>'Learn the basics on how brainstorming can be used to effectively engage employees in obtaining their ideas. In brainstorming, there is that one cardinal rule - No idea is criticized. This app is designed for anyone who wants to effectively solve problems via Total Employee Involvement. Conducting an effective brainstorming session will help facilitate a greater number of ideas, which can very well generate a radical and effective solution.'],
            ['name'=>'Fishbone Diagram','category'=>'Quality Tools','description'=>'Learn the basics on how the Fishbone (or Cause and Effect) Diagram can be used to explore in increasing detail all the possible causes of a problem or issue. If done properly and completely, the cause(s) of the problem should be somewhere listed on the Diagram. This app is designed for anyone who wants to effectively solve problems via Total Employee Involvement. Engaging employees in the Fishbone analysis will help facilitate a greater number of potential solutions on how to improve a process or solve a problem.'],
            ['name'=>'Histogram','category'=>'Quality Tools','description'=>'Learn the basics on how the Histogram can be used effectively to visualize the distribution of numerical data. Analyzing numerical data using the Histogram will help certain data to be better understood as well as statistical information can be obtained. This tool is designed for anyone who wants to effectively solve problems via Total Employee Involvement and data visualization.'],
            ['name'=>'Impact Map ','category'=>'Quality Tools','description'=>'Learn the basics on how the Impact Map will allow teams to identify solutions that are most likely to have the greatest impact on a problem with the least amount of effort. Opportunities and actionable ideas that have a high impact on the organization and are easily completed should take top implementation priority. This tool is designed for anyone who wants to effectively analyze potential solutions or ideas for implementation in a continuous improvement or problem solving project. The Impact Map will help determine the most cost effective, in terms of time and resources, of potential improvement ideas that are being considered.'],
            ['name'=>'Pareto Chart ','category'=>'Quality Tools','description'=>'Learn the basics on how the Pareto Chart turns "data" into useful information. The Pareto Chart uses a bar chart format to visualize the Pareto principle which states that 20% of the sources cause 80% of the problems. This tool is designed for anyone who wants to effectively visualize data in analyzing processes in a continuous improvement or problem solving project. The Pareto Chart will present the data or issues in descending order of importance, which can be used for displaying before and after improvement initiatives.'],
            ['name'=>'Run Chart','category'=>'Quality Tools','description'=>'Learn the basics on how the Run Chart is used to display data points over time. The visual representation of data allows for seeing trends and patterns of an entire process over time. This tool is designed for anyone who wants to effectively visualize data trends and patterns in analyzing processes in a continuous improvement or problem solving project.'],
            ['name'=>'Scatter Plot ','category'=>'Quality Tools','description'=>'Learn the basics on how the Scatter Plot can be used for trends or problematic areas to be easily viewed. The Scatter Plot can reveal relationships between variables as well as help identify "outliers." This tool is designed for anyone who wants to effectively visualize data in analyzing processes in a continuous improvement or problem solving project.'],
            ['name'=>'Stakeholder Analysis ','category'=>'Quality Tools','description'=>'Learn the basics on how the Stakeholder Analysis can be used to identify the key people who have to be influenced for implementation of a project or change initiative. Stakeholder Analysis is critical to the success of every project. Engaging the right people in the right way before, during, and after a project can make a big difference in having any and all changes successfully sustained. This tool is designed for anyone who wants to ensure everyone is on the same page and in support of a continuous improvement or problem solving project.']
        ]);
    }
}